CREATE TABLE `PUBG`.`PUBG_PLAYER` (
  `PLAYER_ID` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `UPDATED_AT` TIMESTAMP NULL,
  `SHARD_ID` CHAR(10) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`)
)
  ENGINE = InnoDB;

ALTER TABLE `PUBG`.`PUBG_PLAYER`
  ADD INDEX `PUBG_PLAYER_NX1` (`NAME` ASC);

CREATE TABLE `PUBG`.`PUBG_PLAYER_MATCH` (
  `PLAYER_ID` VARCHAR(100) NOT NULL,
  `MATCH_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`, `MATCH_ID`)
);
