CREATE TABLE `PUBG`.`PUBG_MATCH_DETAIL` (
  `MATCH_ID` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `DURATION` INT NULL,
  `GAME_MODE` CHAR(10) NULL,
  `MAP_NAME` VARCHAR(45) NULL,
  `SHARD_ID` VARCHAR(10) NULL,
  `TITLE_ID` VARCHAR(45) NULL,
  `DB_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DB_CREATED_BY` VARCHAR(20) NULL,
  `DB_CREATED_FROM` VARCHAR(20) NULL,
  `DB_UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  `DB_UPDATED_BY` VARCHAR(20) NULL,
  `DB_UPDATED_FROM` VARCHAR(20) NULL,
  PRIMARY KEY (`MATCH_ID`),
  INDEX `PUBG_MATCH_DETAIL_NX1` (`CREATED_AT` DESC)
)
  ENGINE = InnoDB;

CREATE TABLE `PUBG`.`PUBG_ROSTER` (
  `MATCH_ID` VARCHAR(100) NOT NULL,
  `ROSTER_ID` VARCHAR(100) NOT NULL,
  `SHARD_ID` VARCHAR(10) NULL,
  `RANK` INT NULL,
  `TEAM_ID` INT NULL,
  `WIN` TINYINT NULL,
  `DB_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DB_CREATED_BY` VARCHAR(20) NULL,
  `DB_CREATED_FROM` VARCHAR(20) NULL,
  `DB_UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  `DB_UPDATED_BY` VARCHAR(20) NULL,
  `DB_UPDATED_FROM` VARCHAR(20) NULL,
  PRIMARY KEY (`ROSTER_ID`),
  INDEX `PUBG_ROSTER_NX1` (`MATCH_ID` ASC),
  INDEX `PUBG_ROSTER_NX2` (`DB_UPDATED_AT` ASC)

)
  ENGINE = InnoDB;

CREATE TABLE `PUBG`.`PUBG_PARTICIPANT` (
  `PARTICIPANT_ID` VARCHAR(100) NOT NULL,
  `MATCH_ID` VARCHAR(100) NOT NULL,
  `ROSTER_ID` VARCHAR(100) NOT NULL,
  `SHARD_ID` VARCHAR(10) NULL,
  `DBNOS` INT NULL,
  `ASSISTS` INT NULL,
  `BOOSTS` INT NULL,
  `DAMAGE_DEALT` Decimal(20, 12) NULL,
  `DEATH_TYPE` VARCHAR(100) NULL,
  `HEADSHOT_KILLS` INT NULL,
  `HEALS` INT NULL,
  `KILL_PLACE` INT NULL,
  `KILL_POINTS` INT NULL,
  `KILL_POINTS_DELTA` Decimal(20, 12) NULL,
  `KILL_STREAKS` INT NULL,
  `KILLS` INT NULL,
  `LAST_KILL_POINTS` INT NULL,
  `LAST_WIN_POINTS` INT NULL,
  `LONGEST_KILL` Decimal(20, 12) NULL,
  `MOST_DAMAGE` INT NULL,
  `NAME` VARCHAR(100) NULL,
  `PLAYER_ID` VARCHAR(100) NULL,
  `REVIVES` INT NULL,
  `RIDE_DISTANCE` Decimal(20, 12) NULL,
  `ROAD_KILLS` INT NULL,
  `TEAM_KILLS` INT NULL,
  `TIME_SURVIVED` INT NULL,
  `VEHICLE_DESTROYS` INT NULL,
  `WALK_DISTANCE` Decimal(20, 12) NULL,
  `WEAPONS_ACQUIRED` INT NULL,
  `WIN_PLACE` INT NULL,
  `WIN_POINTS` INT NULL,
  `WIN_POINTS_DELTA` Decimal(20, 12) NULL,
  `DB_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DB_CREATED_BY` VARCHAR(20) NULL,
  `DB_CREATED_FROM` VARCHAR(20) NULL,
  `DB_UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  `DB_UPDATED_BY` VARCHAR(20) NULL,
  `DB_UPDATED_FROM` VARCHAR(20) NULL,
  PRIMARY KEY (`PARTICIPANT_ID`),
  INDEX `PUBG_PARTICIPANT_NX1` (`MATCH_ID` ASC),
  INDEX `PUBG_PARTICIPANT_NX2` (`ROSTER_ID` ASC),
  INDEX `PUBG_PARTICIPANT_NX3` (`DB_UPDATED_AT` ASC)
)
  ENGINE = InnoDB;





