CREATE TABLE `PUBG`.`PUBG_PLAYER` (
  `PLAYER_ID` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL,
  `UPDATED_AT` TIMESTAMP NULL,
  `SHARD_ID` CHAR(10) NOT NULL,
  `DB_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DB_CREATED_BY` VARCHAR(20) NULL,
  `DB_CREATED_FROM` VARCHAR(20) NULL,
  `DB_UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  `DB_UPDATED_BY` VARCHAR(20) NULL,
  `DB_UPDATED_FROM` VARCHAR(20) NULL,
  PRIMARY KEY (`PLAYER_ID`),
  INDEX `PUBG_PLAYER_NX1` (`CREATED_AT` DESC)
)
  ENGINE = InnoDB;

CREATE TABLE `PUBG`.`PUBG_PLAYER_MATCH` (
  `PLAYER_ID` VARCHAR(100) NOT NULL,
  `MATCH_ID` VARCHAR(100) NOT NULL,
  `SHARD_ID` CHAR(10) NOT NULL,
  `DB_CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DB_CREATED_BY` VARCHAR(20) NULL,
  `DB_CREATED_FROM` VARCHAR(20) NULL,
  `DB_UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP,
  `DB_UPDATED_BY` VARCHAR(20) NULL,
  `DB_UPDATED_FROM` VARCHAR(20) NULL,
  PRIMARY KEY (`PLAYER_ID`, `MATCH_ID`),
  INDEX `PUBG_PLAYER_MATCH_NX1` (`DB_UPDATED_AT` DESC)

);
